resolver: 'lts-22.43'
packages:
- '.'
extra-deps: []
nix:
  packages:
  - graphviz
  - imagemagick
  - texlive.combined.scheme-full  # Just for `standalone.cls`, urgh!
  - zlib
  - openssh
  - rsync
  - pkgconfig
